import { Metadata } from 'next';

// Dynamic metadata will be generated by the page component
// This layout provides fallback SEO
export const metadata: Metadata = {
  title: 'Detail Annonce Immobiliere | ImmoGuinee',
  description: 'Consultez cette annonce immobiliere en Guinee. Location et vente de biens a Conakry : appartements, villas, maisons, terrains.',
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function BienLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
